app/urls.py
from django.urls import path,include

from .models import Item,F_Item
from .views import sendmail,C_View,F_View,ItemFilterView,F_ItemCreateView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

# アプリケーションのルーティング設定

urlpatterns = [
    path('sendmail/', sendmail, name='sendmail'),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('C_View/',C_View,name = 'C_View'),
    path('F_View/',F_View,name = 'F_View'),
    path('f_create/', F_ItemCreateView.as_view(template_name='app/item_form.html'), name='F_create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('', ItemFilterView.as_view(), name='index'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# ルーティング設定
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# 管理サイトの見出しを変更可能
#  タイトル；タイトルタグで使用
admin.site.site_title = 'タイトル'
#  サイト名：ログイン画面と管理画面上部の表示
admin.site.site_header = 'サンプルアプリ'
#  メニュー：管理画面の見出し表示
admin.site.index_title = 'メニュー'

app/models.py
from django.db import models

from users.models import User



class Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/2.1/ref/models/fields/
    """
    # 施設名
    F_name = models.CharField(
        verbose_name='施設名',
        max_length=20,
        blank=True,
        null=True,
    )


    # 入力者氏名
    I_name = models.CharField(
        verbose_name='入力者氏名',
        max_length=20,
        blank=True,
        null=True,
    )

    # サンプル項目2 メモ
    memo = models.TextField(
        verbose_name='備考',
        blank=True,
        null=True,
    )

    # サンプル項目3 整数
    quontity = models.IntegerField(
        verbose_name='何kg出せるか',
        blank=True,
        null=True,
    )



    # サンプル項目7 日付
    deadline = models.DateField(
        verbose_name='いつほしいか',
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（固定）
    vege_choice = (
        (1, '人参'),
        (2, '大根'),
        (3, 'じゃがいも'),
        (4, 'キャベツ'),
        (5, 'ホウレンソウ'),
        (6, 'ピーマン'),
        (7, 'なんでもいい'),
    )

    vegetable = models.IntegerField(
        verbose_name='ほしい野菜',
        choices=vege_choice,
        blank=True,
        null=True,
    )

    address = models.CharField(
        verbose_name='メールアドレス',
        max_length=20,
        blank=True,
        null=True,
    )

    good = models.IntegerField(
        verbose_name = 'いいね',
        null = True,

    )

        # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='C_CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成時間
    created_at = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        editable=False,
    )



    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='C_UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新時間
    updated_at = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        editable=False,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.sample_1

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'サンプル'
        verbose_name_plural = 'サンプル'


class F_Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/2.1/ref/models/fields/
    """
    # 施設名
    F_name = models.CharField(
        verbose_name='施設名',
        max_length=20,
        blank=True,
        null=True,
    )


    # 入力者氏名
    I_name = models.CharField(
        verbose_name='入力者氏名',
        max_length=20,
        blank=True,
        null=True,
    )

    # サンプル項目2 メモ
    memo = models.TextField(
        verbose_name='備考',
        blank=True,
        null=True,
    )

    # サンプル項目3 整数
    quontity = models.IntegerField(
        verbose_name='何kg出そうか',
        blank=True,
        null=True,
    )



    # サンプル項目7 日付
    deadline = models.DateField(
        verbose_name='いつ出そうか',
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（固定）
    vege_choice = (
        (1, '人参'),
        (2, '大根'),
        (3, 'じゃがいも'),
        (4, 'キャベツ'),
        (5, 'ホウレンソウ'),
        (6, 'ピーマン'),
        (7, 'なにかしら'),
    )

    vegetable = models.IntegerField(
        verbose_name='出せる野菜',
        choices=vege_choice,
        blank=True,
        null=True,
    )



    # 以下、管理項目

    # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='F_CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成時間
    created_at = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        editable=False,
    )

    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='F_UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新時間
    updated_at = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        editable=False,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.sample_1

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'サンプル'
        verbose_name_plural = 'サンプル'

app/templates/app/C_View.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th scope="col">Facirity_Name</th>
            <th scope="col">Editer_Name</th scope="col">
            <th scope="col">choice</th>
            <th scope="col">quontity</th>
            <th scope="col">deadline</th>
            <th scope="col">memo</th>
        </tr>

{% for item in data %}
    <tr>
        <td>{{ item.F_name|default_if_none:"未入力" }}</td>
        <td>{{ item.I_name|default_if_none:"未入力" }}</td>
        <td>{{ item.get_vegetable_display|default_if_none:"未入力" }}</td>
        <td>{{ item.quontity|default_if_none:"未入力" }}</td>
        <td>{{ item.deadline|default_if_none:"未入力" }}</td>
        <td>{{item.memo|default_if_none:"未入力"}}</td>
        
    </tr>
{% endfor %}
    </table>
</div>

{% endblock %}

app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>サンプル</title>

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light ">
    <a class="navbar-brand" href="{% url 'index' %}">廃棄野菜有効利用</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">管理画面</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">ログアウト</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"
        charset="UTF-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ja.min.js"></script>
<script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
<script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/item_C_View.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h1>需要リスト</h1>

    <table class="table table-bordered">
        <tr>
            <th scope="col">Facility_Name</th>
            <th scope="col">Editer_Name</th scope="col">
            <th scope="col">choice</th>
            <th scope="col">quantity</th>
            <th scope="col">deadline</th>
            <th scope="col">memo</th>
        </tr>

{% for item in data %}
    <tr>
        <td>{{ item.F_name|default_if_none:"未入力" }}</td>
        <td>{{ item.I_name|default_if_none:"未入力" }}</td>
        <td>{{ item.get_vegetable_display|default_if_none:"未入力" }}</td>
        <td>{{ item.quontity|default_if_none:"未入力" }}</td>
        <td>{{ item.deadline|default_if_none:"未入力" }}</td>
        <td>{{item.memo|default_if_none:"未入力"}}</td>
        
    </tr>
{% endfor %}
    </table>
</div>

{% endblock %}

app/templates/app/item_F_View.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h1>供給リスト</h1>

    <table class="table table-bordered" >
        <tr>
            <th scope="col">Facility_Name</th>
            <th scope="col">Editer_Name</th scope="col">
            <th scope="col">choice</th>
            <th scope="col">quantity</th>
            <th scope="col">deadline</th>
            <th scope="col">memo</th>
        </tr>

{% for item in data %}
    <tr>
        <td>{{ item.F_name|default_if_none:"未入力" }}</td>
        <td>{{ item.I_name|default_if_none:"未入力" }}</td>
        <td>{{ item.get_vegetable_display|default_if_none:"未入力" }}</td>
        <td>{{ item.quontity|default_if_none:"未入力" }}</td>
        <td>{{ item.deadline|default_if_none:"未入力" }}</td>
        <td>{{ item.memo|default_if_none:"未入力"}}</td>
        
    </tr>
{% endfor %}
    </table>
</div>

{% endblock %}

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
    <div class="container">
        <h2 class="text-center">データ削除</h2>
        <p>このデータを削除します。よろしいですか？</p>

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-outline-dark delete" value="削除"/>
                    </div>
                </div>
            </div>
            {% include "./item_detail_contents.html" %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right mb-3">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-outline-dark delete" value="削除"/>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
    <div class="container">
        <h2 class="text-center">詳細表示</h2>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
         
        {% include "./item_detail_contents.html" %}
        
        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>

        <div>

        </div>

    </div>
{% endblock %}

app/templates/app/item_detail_contents.html
<!--
<div class="row">
    <div class="col-5 col-sm-3">
        <p>1_文字列</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_1|default_if_none:"未入力"  }}</p>
    </div>
</div>
-->
<!-- 供給側のページにする -->
<div class="row">
    <div class="col-5 col-sm-3">
        <p>施設名</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.F_name|default_if_none:"未入力"  }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>入力者名</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.I_name|default_if_none:"未入力"  }}</p>
    </div>
</div>

<div class="row">
    <div class="col-5 col-sm-3">
        <p>量</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.quontity|default_if_none:"未入力" }}kg</p>
    </div>
    <!-- 需要側からコンタクトをとれるようにする 
        方法
        1.ログイン実装
        2.メール
        3.他ツールと連携
        メール？
    
    <div class="col-5 col-sm-3">
        <p>メールアドレス</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.address|default_if_none:"未入力" }}</p>
    </div>
-->

    



</div>
<!--
<div class="row">
    <div class="col-5 col-sm-3">
        <p>4_浮動小数点</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_4|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>5_固定小数点</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_5|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>6_ブール値</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_6|yesno:"はい,いいえ" }}</p>
    </div>
</div>
-->
<div class="row">
    <div class="col-5 col-sm-3">
        <p>いつまで</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.deadline|date:"Y年m月d日" }}</p>
    </div>
</div>

<!--
<div class="row">
    <div class="col-5 col-sm-3">
        <p>8_日時</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_8|date:"Y年m月d日 G時i分s秒" }}</p>
    </div>
</div>
-->

<div class="row">
    <div class="col-5 col-sm-3">
        <p>種類</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.get_vegetable_display|default_if_none:"未入力" }}</p>
    </div>
</div>
<!--
<div class="row">
    <div class="col-5 col-sm-3">
        <p>10_選択肢（マスタ連動）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_10.get_full_name|default_if_none:"未入力" }}</p>
    </div>
</div>
-->
<div class="row">
    <div class="col-5 col-sm-3">
        <p>備考</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.memo|default_if_none:"未入力" }}</p>
    </div>
</div>

<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<a class="btn btn-primary" href="{% url 'sendmail' %}">ほしい</a>

app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">検索条件</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body">
                            {{ filter.form|crispy }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <a class="btn btn-outline-dark" data-dismiss="modal">戻る</a>
                        <button type="submit" class="btn btn-outline-dark" form="filter">検索</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                <div class="float-right mt-1">

                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規供給</a>
                    <a class="btn btn-outline-dark" href="{% url 'C_View' %}">供給表</a>

                    
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for item in item_list %}
                        <li class="list-group-item">
                            {# item_detail_contents.html を参考に必要な項目を追加してください #}
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>施設名</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.F_name|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>種類</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.get_vegetable_display|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>いつ</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.deadline|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成者</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_by.get_full_name }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成時間</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="float-right">
                                        <a class="btn btn-outline-dark " href="{% url 'detail' item.pk %}">詳細</a>
                                        <a class="btn btn-outline-dark " href="{% url 'update' item.pk %}">編集</a>
                                        <a class="btn btn-outline-dark " href="{% url 'delete' item.pk %}">削除</a>
                                        
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mt-1 mb-3">
                    
                
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form.certifications.errors }}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center">登録・更新</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                    <a class="btn btn-outline-dark save" href="#">保存</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form method="post" id="myform">
                    {% crispy form %}
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mb-3">
                    <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                    <a class="btn btn-outline-dark save" href="#">保存</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/item_view_Consumer.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th scope="col">Facirity_Name</th>
            <th scope="col">Editer_Name</th scope="col">
            <th scope="col">choice</th>
            <th scope="col">quontity</th>
            <th scope="col">deadline</th>
            <th scope="col">memo</th>
        </tr>

{% for item in data %}
    <tr>
        <td>{{ item.F_name|default_if_none:"未入力" }}</td>
        <td>{{ item.I_name|default_if_none:"未入力" }}</td>
        <td>{{ item.get_vegetable_display|default_if_none:"未入力" }}</td>
        <td>{{ item.quontity|default_if_none:"未入力" }}</td>
        <td>{{ item.deadline|default_if_none:"未入力" }}</td>
        <td>{{item.memo|default_if_none:"未入力"}}</td>
        
    </tr>
{% endfor %}
    </table>
</div>

{% endblock %}

app/templates/app/toppage.html
<!DOCTYPE html>

<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>VegetBanc</title>
        <!-- <link rel="icon" href="favicon.ico"> -->
        <meta name="description" content="廃棄野菜の有効活用の為のサイトです。">
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <header>
            <div class="container">
                <div class="icon">
                    <img src="img/yasai.jpg" width="250" alt="画像">
                </div>
                <div class="info">
                    <h1>VegeBanc</h1>
                    <p>廃棄せざるを得ない野菜の販売・購入を行うサイトです。</p>
                    <ul> 
                        <button type="signup" onclick="location.href='https~~ここに新規登録URLを入れてね'">
                            新規登録
                        </button>
                        <button type="login" onclick="location.href='https~~ここにログインのURLを入れてね'">
                            ログイン
                        </button>
                    </ul>
                </div>
            </div>
        </header>   

        <!-- ここからサイト内 -->

        <section class="view">

            <section>
                <h1>直近の開催日時</h1>
                <p>
                    12/23
                </p>
            </section>

            <section>
                <h1>
                    商品一覧
                </h1>
                <button type="signup" onclick="location.href='https~~ここに商品登録ページのURLを入れてね'">
                    商品ページはこちら
                </button>
            </section>

        </section>

        <footer>
            <p>VegeBanc.com</p>
        </footer>


    </body>

</html>